name: "Terraform Provision Custom Action"
description: "Setup and apply Terraform configurations"
inputs:
  terraform_version:
    description: "Terraform version to use"
    required: true
  tf_workspace:
    description: "Terraform workspace name"
    required: true
  docker_image:
    description: "Docker image to deploy"
    required: true
  tf_api_token:
    description: "Terraform API token"
    required: true
    
outputs:
  app_fqdn:
    description: "Provisioned App FQDN."
    value: ${{ steps.provision.outputs.app_fqdn }}

runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        cli_config_credentials_token: ${{ inputs.tf_api_token }}

    - name: Terraform Init and Apply
      run: |
          cd ./terraform
          export TF_WORKSPACE="${{ inputs.tf_workspace }}"
          terraform init
          terraform apply -auto-approve \
          -var-file="variables/${{ inputs.tf_workspace }}.tfvars" \
          -var="docker_image=${{ inputs.docker_image }}"
          echo "app_fqdn=$(terraform output -raw app_fqdn)" >> $GITHUB_OUTPUT
          cd -
      shell: bash
      env:
        TF_API_TOKEN: ${{ inputs.tf_api_token }}

    
