name: Reusable Terraform Steps

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
      tf_workspace:
        required: true
        type: string
      docker_image:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init and Apply
        run: |
          mkdir -p ${{ github.workspace }}/terraform
          echo "TF_HOME=${{ github.workspace }}/terraform" >> $GITHUB_ENV
          cd ${{ github.workspace }}/terraform
          terraform init
          ls  # This line is optional, just to list files for debugging
          terraform apply -auto-approve \
          -var-file="variables/${{ inputs.tf_workspace }}.tfvars" \
          -var="docker_image=${{ inputs.docker_image }}"
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
