name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01 CI Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_HOME: ${{ github.workspace }}/terraform
      TF_WORKSPACE: dev
      TF_VAR_docker_image: rm1100/juice-shop:${{ github.run_id }}
    steps:
      - name: Download CI Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0" # Specify your required version
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init and Apply
        run: |
          cd ${{ env.TF_HOME }}
          terraform init
          terraform validate
          terraform apply -auto-approve -var-file="prod.tfvars"
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


  production:
    needs: dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          # Add your deployment scripts here
