name: 02 CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the CI pipeline run to reference the Docker image and Terraform artifacts."
        required: true

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: rm1100  # Set your Docker username here
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} # Set Terraform API Token as an environment variable

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Custom Terraform Provisioning for test Environment"
        id: terraform_provision
        uses: ./.github/actions/terrform_provision
        with:
            terraform_version: "1.10.0"
            tf_workspace: "test"
            docker_image: "${{ env.DOCKER_USERNAME }}/juice-shop:${{ github.event.inputs.ci_run_id }}"
            tf_api_token: "${{ env.TF_API_TOKEN }}"
            
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "${{ steps.terraform-provision.outputs.app_fqdn }}"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'


      - name: "Custom Terraform Provisioning for Dev Environment"
        uses: ./.github/actions/terrform_provision
        with:
            terraform_version: "1.10.0"
            tf_workspace: "dev"
            docker_image: "${{ env.DOCKER_USERNAME }}/juice-shop:latest"
            tf_api_token: "${{ env.TF_API_TOKEN }}"
