name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01_CI_Pipeline"]
    branches: [master]
    types:
      - completed
jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: rm1100  # Set your Docker username here or make sure it's set as an environment variable if dynamic
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Check .github directory contents"
        run: ls -la ./.github/actions/terrform_provision

      - name: "Custom Terraform Provisioning for Dev Environment"
        id: terrform_provision
        uses: ./.github/actions/terrform_provision/action.yaml
        with:
          terraform_version: "1.10.0"
          tf_workspace: "dev"
          docker_image: "${{ env.DOCKER_USERNAME }}/juice-shop:latest"
