name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01_CI_Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Check .github directory contents"
        run: ls -la ./.github/actions/terrform_provision

      - name: "Custom Terraform Provisioning for Dev Environment"
        uses: ./.github/actions/terrform_provision/terraform_provision.yaml
        with:
          terraform_version: "1.10.0"
          tf_workspace: "dev"
          docker_image: "${{ secrets.DOCKER_USERNAME }}/juice-shop:latest"

      - name: "Custom Terraform Provisioning for Test Environment"
        uses: ./.github/actions/terrform_provision/terraform_provision.yaml
        with:
          terraform_version: "1.10.0"
          tf_workspace: "test"
          docker_image: "${{ secrets.DOCKER_USERNAME }}/juice-shop:latest"
