name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01_CI_Pipeline"]
    branches: [master]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
    
        - name: Custom Terraform Provisioning
          uses: ./.github/workflows/terraform_provision_Custom_action.yaml@master
          with:
            terraform_version: "1.10.0"
            tf_workspace: dev
            docker_image: "${{ secrets.DOCKER_USERNAME }}/juice-shop:latest"
