name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01_CI_Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  deploy_dev:
    uses: ./.github/actions/terraform_provision_Custom_action.yaml@master
    with:
      terraform_version: "1.10.0"
      tf_workspace: dev
      docker_image: "${{ secrets.DOCKER_USERNAME }}/juice-shop:latest"
