name: 02 CD Pipeline

on:
  workflow_run:
    workflows: ["01_CI_Pipeline"]
    branches: [master]
    types:
      - completed

jobs:
  dev:
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_HOME: ${{ github.workspace }}/terraform
      TF_WORKSPACE: dev
      TF_VAR_docker_image: rm1100/juice-shop:${{ github.run_id }}
    steps:
      - name: Download CI Terraform Artifacts
        uses: actions/download-artifact@v3
        with:
          name: terraform
