name: "CI Pipeline"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      
      - name: "workflow summary"
        run: echo "## Docker Scan Result" >> $GITHUB_STEP_SUMMARY
      
      - name: "Docker Login"
        uses: docker/login-action@v3.3.0
        with:
          username: rm1100
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: "Build and push Docker images"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rm1100/juice-shop:${{ github.run_id }}

      - name: "Docker Scout"
        uses: docker/scout-action@v1.16.1
        with:
          command: "quickview,compare"
          only-severities: critical,high
          exit-code: true
          
