name: "CI Pipeline"

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Docker"
        run: |
          echo "hello this is a test run"
